export 'package:flutter/material.dart';
export 'package:food_delivery/themes/theme_provider.dart';
export 'package:food_delivery/utils/app_colors.dart';
export 'package:provider/provider.dart';
export 'package:food_delivery/widgets/home_drawer.dart';
export 'package:food_delivery/screens/home_screen.dart';
export 'package:food_delivery/screens/register_screen.dart';
export 'package:food_delivery/widgets/custom_button.dart';
export 'package:food_delivery/widgets/custom_text_feild.dart';
export 'package:food_delivery/utils/custom_spacer.dart';
export 'package:food_delivery/screens/login_screen.dart';
export 'package:food_delivery/widgets/my_current_address.dart';
export 'package:food_delivery/widgets/my_sliver_app_bar.dart';
export 'package:food_delivery/widgets/my_description.dart';
export 'package:food_delivery/widgets/my_tab_bar.dart';
// export
// export
// export
// export
// export
// export
// export
// export
